name: CI/CD AWS CDK

on:
  push:
    branches:
      - master

env:
  S3_BUCKET_NAME: "vlad-test-deploy-2021"
  AWS_REGION: "us-east-1"

jobs:
  build:
    name: My build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Select repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - name: Clean install dependencies and build
      env:
        CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
        CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
        MAILCHIMP_ENDPOINT: ${{secrets.MAILCHIMP_ENDPOINT}}

    - name: CI
      run:
        npm ci
        npm run develop



    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create and Deploy AWS Resources
      uses: ./cdk-toolkit/cdk/lib/cdk-stack.ts

    - name: Copy files to the production website with the AWS CLI
      run:
        aws s3 sync public s3://${{ env.S3_BUCKET_NAME }}
