name: CI/CD AWS CDK execution

on:
  push:
    branches:
      - master

env:
  S3_BUCKET_NAME: "vlad-test-deploy"
  AWS_REGION: "us-east-1"

jobs:
  build:
    name: Build performance
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean install dependencies and build
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        MAILCHIMP_ENDPOINT: "https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/?=mailchimp#mailchimp-endpoint"
      run:
        npm ci
        npm run build

  infrastructure:
    name: Infrastructure formation
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: CDK install
      run: npm install -g aws-cdk
    - name: CDK bootstrap
      run: cdk bootstrap
    - name: CDK synth
      run: cdk synth
    - name: CDK deploy
      run: |
            aws s3 rm s3://${{ env.S3_BUCKET_NAME }}
            aws s3 sync . s3://${{ env.S3_BUCKET_NAME }}/

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}



